ログイン機能の実装
yanbaru-expert/team_project_48 pull request #14
Opened 2021-04-13 12:53 UTC by mihomatsui

## issue 番号

close #11

## 実装内容

- ログイン機能の実装
  - gemのインストールと設定ファイルの作成
  - ログイン機能に対応したUserモデルの作成  
  - 新規登録・ログイン・ログアウトのリンクを全てのページの一番上に追加
  - db/seeds.rbにテスト用ユーザーを作成できるように設定
  - 全てのページをログイン必須に変更

## 参考資料（必要があれば）
  - [やんばるエキスパートアプリ](https://www.yanbaru-code.com/texts/219)
  - [【公式】devise](https://github.com/heartcombo/devise)

## チェックリスト

- [ ] GitHub で Files changed を確認
- [ ] 影響し得る範囲のローカル環境での動作確認

2021-04-13 13:04 UTC, ajk0421 requested changes

2021-04-13 13:04 UTC, ajk0421 commented on app/views/layouts/application.html.erb
> +         <% end %>
表示される場所はあっていますか？？

2021-04-13 13:04 UTC, ajk0421 commented on app/controllers/texts_controller.rb
> +  before_action :authenticate_user!
この記述ですが、例えば
```
MoviesController
```
を追加で実装する場合どうしますか？？

2021-04-13 22:41 UTC, mihomatsui commented on app/views/layouts/application.html.erb
> +         <% end %>
間違っていると思ったので、ヘッダーに表示されるように修正致しました。

2021-04-13 22:45 UTC, mihomatsui commented on app/controllers/texts_controller.rb
> +  before_action :authenticate_user!
MoviesControllerを追加で実装する場合、こちらもbefore_actionの記述が必要になりますね。

- 重複する箇所は統一する
- 継承を利用する
以上のことを考え、TextsControllerではなくApplicationControllerにbefore_actionを移動しました。

2021-04-14 07:26 UTC, ajk0421 requested changes

2021-04-14 07:26 UTC, ajk0421 commented on app/views/layouts/application.html.erb
> +        <% end %>
ここインデントずれてませんか？？

2021-04-14 11:20 UTC, mihomatsui commented on app/views/layouts/application.html.erb
> +        <% end %>
ずれていたので修正しました。

2021-04-14 12:48 UTC, ajk0421 approved these changes
OKです！
マージしてください！

2021-04-14 12:57 UTC, merged