日本語化
yanbaru-expert/team_project_48 pull request #30
Opened 2021-04-18 08:07 UTC by mihomatsui

## issue 番号

close #16

## 実装内容
- 日本語化
  - rails-i18nとdevise-i18nのgemを追加
  - タイムゾーンの変更と言語を日本語に設定
  - config/application.rbのコンフリクトを解消 

## 参考資料（必要があれば）
- 日本語化
  - [【公式】rails-i18n](https://github.com/svenfuchs/rails-i18n)
  -  [【公式】devise-i18n](https://github.com/tigrish/devise-i18n)
  - [やんばるエキスパート教材（ログイン機能）](https://www.yanbaru-code.com/texts/219)

## チェックリスト

【補足】プルリクを出した後，クリックしてチェックを入れて下さい

- [ ] GitHub で Files changed を確認
- [ ] 影響し得る範囲のローカル環境での動作確認

2021-04-18 11:09 UTC, ajk0421 requested changes
基本的に必要なymlファイルは設置してください！

2021-04-20 14:24 UTC, mihomatsui reviewed
すみませんでした。ymlファイルを設置しました。

2021-04-20 14:24 UTC, mihomatsui commented on config/locales/ja.yml
> +ja:
[管理者画面(ActiveAdmin)](https://www.yanbaru-code.com/texts/220)のja.ymlを参考にしました。

2021-04-21 03:34 UTC, ajk0421 approved these changes
OKです！
マージしてください！

2021-04-21 03:40 UTC, merged