ナビバーの実装
yanbaru-expert/team_project_48 pull request #31
Opened 2021-04-23 13:16 UTC by itstoasted-0

## issue 番号

close #19 

## 実装内容

- Bootstrapを使い，逆転教材のナビバーに近いものを作成。
  - 直接 application.html.erb に書き込まず，部分テンプレート app/views/layouts/_header.html.erb を作成して読み込むよう実装
  - 「タスク6」で作成された「新規登録・ログアウトなどのリンク」は削除
  - 「新規登録」のリンクも付けて下さい
  - ナビバーのリンクは，「新規登録」「ログイン」「ログアウト」と，「テキスト教材」ページのみ有効にし，他は href 属性を # にしておく。
  - ナビバーは fixed-top クラスを利用して上に固定されるようにすること。また，ナビバーに隠れないようなスタイルの調整。

## 参考資料

- ナビバーの実装
  - [やんばるエキスパートアプリ](https://www.yanbaru-code.com/texts/271)
  - [Bootstrap Navbar](https://getbootstrap.jp/docs/4.5/components/navbar)

## チェックリスト

- [ ] GitHub で Files changed を確認
- [ ] 影響し得る範囲のローカル環境での動作確認

2021-04-23 13:17 UTC, itstoasted-0 commented on app/views/layouts/application.html.erb
> +    <header class='fixed-top base-bg-color'>
ナビバーの上部固定と背景のグラデーションの為のクラスを設定

2021-04-23 13:19 UTC, itstoasted-0 commented on config/routes.rb
> +  resources :texts
ヘッダーからのテキスト教材のリンクを実装する為に記述

2021-04-24 05:01 UTC, ajk0421 requested changes
![スクリーンショット 2021-04-24 13 54 31](https://user-images.githubusercontent.com/43706278/115947872-92b9c600-a505-11eb-8087-98cbfe776664.png)
フラッシュメッセージの位置がおかしいですね！

2021-04-26 08:17 UTC, itstoasted-0 commented
![スクリーンショット 2021-04-26 17 16 09](https://user-images.githubusercontent.com/75562508/116051091-31375a00-a6b3-11eb-84d4-9fdc8cb6c3a1.png)
表示を変更いたしました。

2021-04-26 08:36 UTC, ajk0421 approved these changes
OKです！マージしてください！

2021-04-26 08:37 UTC, merged