管理者画面の実装
yanbaru-expert/team_project_48 pull request #32
Opened 2021-04-24 08:56 UTC by naotsugukaneko

## issue 番号
close #25 

## 実装内容
- 管理者画面を追加
  - rails-i18n, devise-i18n の追加はタスク7で完了済
  - ja.yml の設定はタスク11で完了済
  - 通常ログインなしでも管理者画面のログインが可能
- db/seeds.rb をタスク6と同様の形式（何度実行してもエラーが出ない形式）に修正
- ユーザー，動画，テキスト教材を管理者画面から追加できるように設定
- 管理者画面以外のスタイルに影響が出ないように対処

## 参考資料（必要があれば）
- [管理者画面(ActiveAdmin)](https://www.yanbaru-code.com/texts/220)

## チェックリスト
- [ ] GitHub で Files changed を確認
- [ ] 影響し得る範囲のローカル環境での動作確認

## スクリーンショット
- 管理者画面
<img width="1680" alt="スクリーンショット 2021-04-24 17 38 04" src="https://user-images.githubusercontent.com/77927517/115953409-43d05880-a526-11eb-87ff-dcdd2342d98c.png">
- モデル名・カラム名の日本語化
<img width="1668" alt="スクリーンショット 2021-04-24 17 39 21" src="https://user-images.githubusercontent.com/77927517/115953422-5d71a000-a526-11eb-92a1-ba5de26cc034.png">
<img width="1668" alt="スクリーンショット 2021-04-24 17 39 53" src="https://user-images.githubusercontent.com/77927517/115953427-66fb0800-a526-11eb-9d7a-86ef0e4a5f4e.png">

2021-04-24 11:28 UTC, ajk0421 requested changes
https://github.com/yanbaru-expert/team_project_48/pull/32#issue-622550493

こちらの `実装内容` に書かれている内容の動作確認は行いましたか？

2021-04-24 11:28 UTC, ajk0421 commented on db/seeds.rb
> +  admin_user.password_confirmation = PASSWORD
```
admin_user.password_confirmation = PASSWORD
```
この記述は必要でしょうか？？

2021-04-24 11:28 UTC, ajk0421 commented on app/controllers/application_controller.rb
> +    def authenticate!
まずインデントがズレてますが、ここはどういった実装がしたくて書いたコードでしょうか？

2021-04-24 14:15 UTC, naotsugukaneko reviewed
> [#32 (comment)](https://github.com/yanbaru-expert/team_project_48/pull/32#issue-622550493)
> 
> こちらの `実装内容` に書かれている内容の動作確認は行いましたか？

動作確認しました。
実装前はadmin/loginのURLにした場合、users/sign_inにリダイレクトされましたが、実装後はユーザーでサインインしてなくても管理者画面にログインできるようになりました。

2021-04-24 14:27 UTC, naotsugukaneko commented on db/seeds.rb
> +  admin_user.password_confirmation = PASSWORD
確認不足でした。
activeadminインストール時に最初から記述がありましたのでそのまま載せておりました。
調べたのですが、 `admin_user.password_confirmation = PASSWORD` は新規登録時にパスワード確認用に記述する場合に必要で管理者アカウントはそもそも今回、新規作成の昨日を実装していないので「いらない」という認識であってますでしょうか？

2021-04-24 14:29 UTC, naotsugukaneko commented on app/controllers/application_controller.rb
> +    def authenticate!
インデント修正しました。
こちらはセルフレビューで記述させて頂いたように、`通常ログイン無しで管理者画面にログインできるように設定` したのですがそういう質問ではなく質問の意図の理解を間違えてますでしょうか？

2021-04-25 00:42 UTC, ajk0421 commented on db/seeds.rb
> +  admin_user.password_confirmation = PASSWORD
既に書かれている

```
# テストユーザーが存在しないときだけ作成
User.find_or_create_by!(email: EMAIL) do |user|
  user.password = PASSWORD
  puts "ユーザーの初期データインポートに成功しました。"
end
```

こちらがヒントになるのですが、この場合はpassword_confirmationを記述しなくてもレコードを作成できます！
あっても作成できるので完全に間違いというわけでは無いですが、必要無いコードをなるべく書かない方が良いでいすね！

2021-04-25 00:56 UTC, ajk0421 commented on app/controllers/application_controller.rb
> +    def authenticate!
>こちらはセルフレビューで記述させて頂いたように

あ、それであれば、僕が見逃していたかもしれません。

>通常ログイン無しで管理者画面にログインできるように設定

とのことですが、僕の手元で確認出来ません。僕の解釈が違いますか？？

※ 下記参照

![Apr-25-2021 09-53-19](https://user-images.githubusercontent.com/43706278/115976781-74f36c00-a5ac-11eb-83a7-bdc1f49326ac.gif)

2021-04-25 02:38 UTC, ajk0421 commented on app/controllers/application_controller.rb
> +    def authenticate!
>こちらはセルフレビューで記述させて頂いたように

すみません。こちら気づきませんでした。(どこに書いてました？？)
あと、この実装ですが、何か記事を参考にされましたか？

あれば、レビューの参考にさせて頂ければと。

2021-04-25 02:39 UTC, ajk0421 commented
> > [#32 (comment)](https://github.com/yanbaru-expert/team_project_48/pull/32#issue-622550493)
> > こちらの `実装内容` に書かれている内容の動作確認は行いましたか？
> 
> 動作確認しました。
> 実装前はadmin/loginのURLにした場合、users/sign_inにリダイレクトされましたが、実装後はユーザーでサインインしてなくても管理者画面にログインできるようになりました。


`ユーザー，動画，テキスト教材を管理者画面から追加できるように設定`

こちらは確認してますか？？

2021-04-26 05:41 UTC, naotsugukaneko commented on db/seeds.rb
> +  admin_user.password_confirmation = PASSWORD
承知しました。
ありがとうございます！

2021-04-26 05:48 UTC, naotsugukaneko commented on app/controllers/application_controller.rb
> +    def authenticate!
間違っていたら申し訳ありません。
セルフレビューは「何故そのコードを追加したか」の事かと思いましたので、
> 通常ログイン無しで管理者画面にログインできるように設定致しました。
と記載したのみでした🙇‍♂️

ユーザーサインイン無しでも管理者画面にログインできるよう [deviseのヘルパーへソッドが使用できない](https://teratail.com/questions/126207) の記事を参考にして実装しました。
👆このように記載が必要だったということでしょうか？

2021-04-26 07:34 UTC, naotsugukaneko commented
> > > [#32 (comment)](https://github.com/yanbaru-expert/team_project_48/pull/32#issue-622550493)
> > > こちらの `実装内容` に書かれている内容の動作確認は行いましたか？
> > 
> > 
> > 動作確認しました。
> > 実装前はadmin/loginのURLにした場合、users/sign_inにリダイレクトされましたが、実装後はユーザーでサインインしてなくても管理者画面にログインできるようになりました。
> 
> `ユーザー，動画，テキスト教材を管理者画面から追加できるように設定`
> 
> こちらは確認してますか？？

申し訳ありません。確認漏れておりました。
確認したところ追加できず、動画と教材については追加できるように修正完了致しました。
<img width="1662" alt="スクリーンショット 2021-04-26 15 05 51" src="https://user-images.githubusercontent.com/77927517/116043287-6f7c4b80-a6aa-11eb-8575-0eb120535d9b.png">
<img width="1673" alt="スクリーンショット 2021-04-26 15 05 26" src="https://user-images.githubusercontent.com/77927517/116043321-7a36e080-a6aa-11eb-9112-cb939ba4aefb.png">

しかしユーザーだけ追加ができません🙇‍♂️
現在管理者画面での新規ユーザー作成カラムで
``` t.string :email
t.string   :reset_password_token
t.datetime :reset_password_sent_at
t.datetime :remember_created_at ```
こちらが表示されていると思います。

本当はユーザーを追加するのに
・Eメール
・パスワード
・確認用パスワード
こちらのカラムにしたいです。
これはapp/admin/users.rbで上記カラムの入力が間違っているという認識でよろしかったでしょうか？

2021-04-26 08:30 UTC, ajk0421 commented on app/controllers/application_controller.rb
> +    def authenticate!
>ユーザーサインイン無しでも管理者画面にログインできるよう deviseのヘルパーへソッドが使用できない の記事を参考にして実装しました。
👆このように記載が必要だったということでしょうか？

あ、こちらがあると分かりやすいですね！！


ただ、このコードだと、穴があります！
どういう状況かというと、管理画面にログインした後だと、通常画面でログインしていなくても、ログイン後の画面が見えてしまいますね。

※ 下記画像参照

![チーム開発_やんばるエキスパート教材クローン](https://user-images.githubusercontent.com/43706278/116052445-96d81600-a6b4-11eb-97db-f5c132ce8e81.png)


以下が再現手順になるので、実際に手元で試して、この現像が起きないようにしましょう！
難しければ、通常画面でログイン後じゃないと管理画面に行けない。という仕様にするのも有りです！

1. 通常画面からログアウトした状態にする
2. 管理画面にログインする
3. `/` にURLを直接してして、遷移する

2021-04-26 08:33 UTC, ajk0421 commented
> これはapp/admin/users.rbで上記カラムの入力が間違っているという認識でよろしかったでしょうか？

そうですね！
「カラムの入力」という表現が正しいかは分かりませんが、上記にファイルを修正する必要があります！

2021-04-26 13:35 UTC, naotsugukaneko commented on app/controllers/application_controller.rb
> +    def authenticate!
> 管理画面にログインした後だと、通常画面でログインしていなくても、ログイン後の画面が見えてしまいますね。

「新規登録ボタン」が出ていることも含めて確認不足でした💦

今回は教材の `config/initializers/active_admin.rb` に `config.skip_before_action :authenticate_user!` を追加して通常ログイン無しで管理者ログインするを実装に変更しました。(教材確認不足で一番下まで見ておりませんでした🙇‍♂️)
しかしせっかく教えて頂いた再現手順も理解できるように調べてみます！
お忙しい中教えて頂きありがとうございました。

2021-04-26 13:37 UTC, naotsugukaneko commented
> > これはapp/admin/users.rbで上記カラムの入力が間違っているという認識でよろしかったでしょうか？
> 
> そうですね！
> 「カラムの入力」という表現が正しいかは分かりませんが、上記にファイルを修正する必要があります！

2021-04-26 13:46 UTC, naotsugukaneko commented
> 「カラムの入力」という表現が正しいかは分かりません

フォームのカスタマイズですかね？申し訳ありません😅

色々調べている間に [こちらの記事](https://blog.mmmcorp.co.jp/blog/2015/02/18/activeadmin/) を見つけまして、少し古かったのですが参考にさせて頂き、自分なりに考えて実装してみました！
こちら実装後の動作確認画面です。
<img width="1550" alt="スクリーンショット 2021-04-26 22 27 16" src="https://user-images.githubusercontent.com/77927517/116092952-38755c80-a6e1-11eb-842a-94a5c0ba6b63.png">
<img width="1564" alt="スクリーンショット 2021-04-26 22 26 44" src="https://user-images.githubusercontent.com/77927517/116092973-3ca17a00-a6e1-11eb-9e63-584fbcad33e2.png">

よろしくお願い致します。

2021-04-26 23:08 UTC, ajk0421 approved these changes
OKです！マージしてください！

2021-04-27 13:13 UTC, merged