devise関連ページのスタイルを修正
yanbaru-expert/team_project_48 pull request #34
Opened 2021-04-28 20:15 UTC by takayanagi-takesi

#24 issue devise関連ページのスタイルを修正

【備考】「close #issue番号」を記載することで，プルリクがマージされると同時に issue が close されるようになります

（例）
close #1

ログイン関連ページを日本語化

・ビューファイルを作成する際は，多言語対応のビューファイルを作成できる` rails g devise:i18n:views `を使用すること。
Bootstrapを利用してスタイルを修正

・`devise-bootstrap-views` のgemを追加してビューファイルを上書き
※フラッシュは「タスク13」で追加しますので対応不要です ※パスワード再設定用のメール送信機能については何もしなくてOKです

## 参考資料（必要があれば）
[・ログイン機能（Devise・日本語化・Bootstrap4）](https://www.youtube.com/watch?v=Ta6CbQGX5Co)

## チェックリスト

【補足】プルリクを出した後，クリックしてチェックを入れて下さい

- [ ] GitHub で Files changed を確認
- [ ] 影響し得る範囲のローカル環境での動作確認

## スクリーンショット（必要があれば）

-
<img width="544" alt="スクリーンショット 2021-04-29 4 26 18" src="https://user-images.githubusercontent.com/75218115/116464338-d23a3680-a8a6-11eb-94aa-239a616b822f.png">
<img width="809" alt="スクリーンショット 2021-04-29 4 27 04" src="https://user-images.githubusercontent.com/75218115/116464346-d36b6380-a8a6-11eb-8629-1a8787251f3b.png">

## 備考（必要があれば）

2021-04-30 15:54 UTC, takayanagi-takesi reviewed
Bootatrapにて下記のスタイル変更(ログイン画面、新規登録画面、パスワード忘れ画面)
・入力バーの長さ
・バリデーションの追加

2021-05-01 14:29 UTC, mihomatsui commented
<img width="600" alt="プルリク#34" src="https://user-images.githubusercontent.com/70443334/116785275-9d5ef700-aad3-11eb-9276-a452fe414c90.png">

- パスワードを忘れましたか？の改行が気になりますね。
- チェックリストのチェックが抜けているので、動作確認等されていたら入れましょう！

2021-05-09 02:50 UTC, ajk0421 requested changes
コンフリクト解消後にログイン画面等、ご自分が実装した箇所を確認しましたか？？

2021-05-09 02:50 UTC, ajk0421 commented on app/views/devise/confirmations/new.html.erb
> +   </div>
```suggestion
<div class="container-login">
  <h1><%= t('.resend_confirmation_instructions') %></h1>

  <%= form_for(resource, as: resource_name, url: confirmation_path(resource_name), html: { method: :post }) do |f| %>
    <%= bootstrap_devise_error_messages! %>

    <div class="form-group">
      <%= f.label :email %>
      <%= f.email_field :email, autofocus: true, autocomplete: 'email', value: (resource.pending_reconfirmation? ? resource.unconfirmed_email : resource.email), class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.submit t('.resend_confirmation_instructions'), class: 'btn btn-primary btn-block' %>
    </div>
  <% end %>

  <%= render 'devise/shared/links' %>
</div>
```

全体的に余計な空白が入ってるとこがあるの `他のファイルも` 見直してみてください！

2021-05-09 02:50 UTC, ajk0421 commented on app/views/layouts/application.html.erb
> +<<<<<<< HEAD
👀

2021-05-13 16:28 UTC, ajk0421 requested changes

2021-05-13 16:28 UTC, ajk0421 commented on app/views/layouts/application.html.erb
> +</html>
ここのインデントが全体的にずれてしまっているので、修正前を参考に訂正してください！

2021-05-17 01:34 UTC, ajk0421 approved these changes
OKです！マージしてください！

2021-05-17 12:11 UTC, merged