動画教材の視聴済みボタンを実装
yanbaru-expert/team_project_48 pull request #45
Opened 2021-05-30 15:54 UTC by naotsugukaneko

## issue 番号
close #43 

## 実装内容
- 「視聴済みにする」・「視聴済みを解除する」ボタンの実装
  - Watchモデル作成,Userモデル・Movieモデルと関連付け(多対多)
  - 非同期処理に変更

## 参考資料（必要があれば）
- [やんばるエキスパート教材 モデルの関連付け その2(多対多)](https://www.yanbaru-code.com/texts/297)
- [【Rails】link_toをボタンにする。(Qiita記事)](https://qiita.com/maru_katy/items/5d352951161ebd9b2e3a)
- [【Rails】 link_toの使い方をマスターして簡単にリンクを作成しよう！
(Pikawaka)](https://pikawaka.com/rails/link_to)

## チェックリスト
- [ ] GitHub で Files changed を確認
- [ ] 影響し得る範囲のローカル環境での動作確認

## スクリーンショット（必要があれば）
- test@example.comユーザーでログイン時
<img width="1503" alt="スクリーンショット 2021-05-31 0 28 39" src="https://user-images.githubusercontent.com/77927517/120110719-9c3fe900-c1a9-11eb-8ec9-5b168850538b.png">
- satou@example.comユーザーでログイン時
<img width="1505" alt="スクリーンショット 2021-05-31 0 30 00" src="https://user-images.githubusercontent.com/77927517/120110753-cd201e00-c1a9-11eb-853b-0cad2386bc57.png">

## 備考（必要があれば）
- 苦戦した箇所
  - 多対多の関連付け
  - ボタンデザイン
    - Bootstrapの公式ドキュメントだけでは実装できませんでした

2021-06-02 13:57 UTC, mihomatsui requested changes

2021-06-03 13:05 UTC, naotsugukaneko commented on app/models/movie.rb
> +  has_many :wacthed_users, through: :watches, source: :user
おっしゃる通りです🙇‍♂️
ありがとうございます、修正しました！

2021-06-03 13:05 UTC, naotsugukaneko commented on app/models/movie.rb
> +  has_many :wacthed_users, through: :watches, source: :user
おっしゃる通りです🙇‍♂️
ありがとうございます、修正しました！

2021-06-08 06:30 UTC, ajk0421 requested changes

2021-06-08 06:30 UTC, ajk0421 commented on app/controllers/watches_controller.rb
> +  end
```
def set_message
   @movie = Movie.find(params[:movie_id])
 end
```

ここがメソッド名と内容が乖離してるので、直しましょう！

2021-06-08 06:30 UTC, ajk0421 commented on db/seeds.rb
> +user3 = User.create!(email: "tanaka@example.com", password: "password")
この辺は残しておいて大丈夫ですか？？

2021-06-11 05:14 UTC, naotsugukaneko commented on app/controllers/watches_controller.rb
> +  end
確認不足でした💦
意味がわかるよう書き換えます！

2021-06-11 07:30 UTC, ajk0421 requested changes
- https://github.com/yanbaru-expert/team_project_48/pull/45/files#diff-c691566e1c70c7ef3c2591320b06724afef84b0d9d8f9ed97d132c3d1c0663adR2-R5
- https://github.com/yanbaru-expert/team_project_48/pull/45/files#diff-9802ca3c9c4cf89904fd44bc114e35ebdf2c5dd3d5b645491e2b253e1afef29bR2-R5

上記にアソシエーションが本当に正しいか今一度見直してみましょう！

2021-06-13 07:35 UTC, naotsugukaneko commented
改めてアソシエーションを考えてみる為、ER図を作成しました。
<img width="542" alt="スクリーンショット 2021-06-13 16 19 38" src="https://user-images.githubusercontent.com/77927517/121799062-d65ac180-cc64-11eb-91d3-c486099a5a98.png">

userとmovieの関連付けは必要ないという考えに至ったのですがそちらで合ってますでしょうか？
それぞれのモデルで関連付け(has_many,belongs_to)を外し動作確認しているのですが、今度は下記のようなエラーになっております。
``` ActionView::Template::Error (Association named 'user' was not found on Movie; perhaps you misspelled it?
Did you mean?  watches):
    1: <div class="container-fluid">
    2:   <div class="row">
    3:     <% @movies.each.with_index(1) do |movie, i| %>
    4:       <div class="col-12 col-md-6 col-lg-4">
    5:         <div class="card border-dark mb-3" style="height: 23rem;">
    6:           <div class="card-header p-0">
  
app/views/movies/_movie.html.erb:3
app/views/movies/index.html.erb:4 ```
ここまでの考え方があっているか教えて頂けないでしょうか？
よろしくお願い致します。

2021-06-13 08:45 UTC, ajk0421 commented
https://github.com/yanbaru-expert/team_project_48/pull/45/files#diff-9802ca3c9c4cf89904fd44bc114e35ebdf2c5dd3d5b645491e2b253e1afef29bR2

https://github.com/yanbaru-expert/team_project_48/pull/45#issuecomment-860167711

双方を見比べると、コーディングと実際に想定されているアソシエーションが違うと思います。


https://github.com/yanbaru-expert/team_project_48/pull/45#issuecomment-860167711

こちらが正しいと思うので、この図を元にコーディングしていましょう！！！

2021-06-14 23:53 UTC, naotsugukaneko commented
申し訳ありません、ヒントを頂いたのに解決できません…🙇‍♂️
アソシエーションを上記のER図のように設定する場合、
userモデルの `has_many :movies, dependent: :destroy`
movieモデルの `belongs_to :user`
を削除しました。
その場合、 `rails db:seed` は問題なく処理されました。
しかし動作確認の際、動画教材ページ確認時に下記のようなエラーとなります。
```
ActionView::Template::Error (Association named 'user' was not found on Movie; perhaps you misspelled it?
Did you mean?  watches):
    1: <div class="container-fluid">
    2:   <div class="row">
    3:     <% @movies.each.with_index(1) do |movie, i| %>
    4:       <div class="col-12 col-md-6 col-lg-4">
    5:         <div class="card border-dark mb-3" style="height: 23rem;">
    6:           <div class="card-header p-0">
  
app/views/movies/_movie.html.erb:3
app/views/movies/index.html.erb:4
```
こちらはmovieモデルにuserとのアソシエーションが見つかりませんといったエラーだと思うのですが、エラー文の@moviesでエラーが発生しており@moviesはモデルをインスタンス化したものなので結局movieモデルに問題があるという認識でよろしかったでしょうか？

◆試したこと
movieモデルの ``belongs_to :user` だけ残す
➡︎エラーはなくなり動作確認はできますが、 `rails db:seed` で下記エラーが発生し最初の問題に戻ってしまいます。
```
テキスト教材インポート処理を開始
インポート完了!!
動画教材インポート処理を開始
rails aborted!
ActiveRecord::RecordInvalid: バリデーションに失敗しました: Userを入力してください
/home/ubuntu/environment/rails/team_project_48/lib/autoloads/import_csv.rb:24:in `movie_data'
/home/ubuntu/environment/rails/team_project_48/db/seeds.rb:19:in `<main>'
/home/ubuntu/environment/rails/team_project_48/bin/rails:5:in `<top (required)>'
/home/ubuntu/environment/rails/team_project_48/bin/spring:10:in `block in <top (required)>'
/home/ubuntu/environment/rails/team_project_48/bin/spring:7:in `tap'
/home/ubuntu/environment/rails/team_project_48/bin/spring:7:in `<top (required)>'
Tasks: TOP => db:seed
(See full trace by running task with --trace)
```

正直、頭がこんがらがってしまいわからなくなってしました。
アソシエーションはER図が正しいとすれば各モデルのアソシエーションは削除したとして他の記述が必要になってくるのでしょうか？

2021-06-15 13:49 UTC, naotsugukaneko commented
- [ ] UserとMovieのアソシエーション解消後の動作確認
- [ ] `rails db:seed` 実行後のエラー解消
上記どちらも確認済みです。

2021-06-16 05:28 UTC, ajk0421 requested changes

2021-06-16 05:28 UTC, ajk0421 commented on app/models/user.rb
> +  # has_many :movies, dependent: :destroy
コメントアウトしてますが、今後使う予定はありますか？

2021-06-16 13:50 UTC, naotsugukaneko commented on app/models/user.rb
> +  # has_many :movies, dependent: :destroy
削除しました🙇‍♂️

2021-06-18 02:55 UTC, ajk0421 approved these changes

2021-06-22 03:30 UTC, mihomatsui approved these changes

2021-06-22 04:28 UTC, merged