Rails動画教材ページのページネーションの実装
yanbaru-expert/team_project_48 pull request #47
Opened 2021-06-03 14:07 UTC by mihomatsui

## issue 番号

close #44

## 実装内容

- Rails動画教材ページのページネーションの実装
  - kaminariのgemを導入
  - moviesのコントローラーとビューにページネーションを追加
  -  ページ移動に対応したLv番号が表示されるよう実装
  - kaminariのテンプレートファイルの作成
  - ページネーションを中央に配置

## 参考資料（必要があれば）
- 関連タスク
  - [Bootstrapの導入 #21](https://github.com/yanbaru-expert/team_project_48/pull/21)

- ページネーションの導入
    - [【初心者向け】ページネーションを付けたページにおける項目番号取得（クラスメソッドの定義まで）](https://qiita.com/koumura2501/items/15169d3284366191850a)
  - [kaminari徹底入門](https://qiita.com/nysalor/items/77b9d6bc5baa41ea01f3)
- 中央に配置・Bootstrap使用
  -   [【Rails】kaminari + Bootstrapで見た目を整え、ページネーションを中央にする](https://qiita.com/shun-takahashi/items/ed45d76e0f011e4f5b7b)

## チェックリスト
- [ ] GitHub で Files changed を確認
- [ ] 影響し得る範囲のローカル環境での動作確認

## スクリーンショット（必要があれば）
- ページネーション
<img width="500" alt="ページネーション中央寄せ" src="https://user-images.githubusercontent.com/70443334/120656287-74f55e80-c4be-11eb-9b3c-3b3a884375b2.png">

- Lvの確認（現在1ページで表示される件数を8件と設定→2ページ目はLv9から表記）
<img width="500" alt="Lvの確認" src="https://user-images.githubusercontent.com/70443334/120656896-f51bc400-c4be-11eb-9ee3-c29d82197ca9.png">

- ページネーションのデザイン（ページ数が多い時）
<img width="500" alt="ページ数が多い時" src="https://user-images.githubusercontent.com/70443334/120657266-4f1c8980-c4bf-11eb-8d34-3e939e5beda7.png">

## 備考（必要があれば）
- 苦労した点
　動画のLvの表示の実装（indexをそのまま使用すると、ページの頭が常にLv1からのスタートになるため修正）
- 現在1ページで表示される件数を仮で8件と設定してあります。
　

2021-06-05 03:58 UTC, ajk0421 requested changes

2021-06-05 03:58 UTC, ajk0421 commented on app/controllers/movies_controller.rb
> +    @movies = Movie.where(genre: ["basic", "git", "ruby", "rails"]).order(id: :asc).page(params[:page]).per(PER)
ここは `scope` でまとめてみましょう！

2021-06-05 03:58 UTC, ajk0421 commented on app/controllers/movies_controller.rb
> +    @base_level = (page_num - 1) * PER
ここの内容がよく分からないので説明頂いても良いですか？

2021-06-05 14:33 UTC, mihomatsui commented on app/controllers/movies_controller.rb
> +    @base_level = (page_num - 1) * PER
[こちら](https://qiita.com/koumura2501/items/15169d3284366191850a)のQiitaの記事を参考に実装しました。

動画教材の中にLvの表示があり、他のページに移動した際に
元々の`app/views/movies/_movie.html.erb`内の`@movies.each.with_index(1)`で取り出す記述だと、
どのページに移動しても始まりが1からになってしまうため、連番で表示させたいと考えました。
(1ページに8件ずつ表示されると設定したら、2ページ目はLv9から表示させたい。)

①page_num（現在のページ）で現在のページを取得
②base_level  (土台水準)で前ページの一番最後のLvの値を取得

(例) PER = 8（1ページに8件ずつ表示されると設定）
page_num = 2の時（2ページ目にいる時）
@base_level = (page_num - 1) * PER =  (2-1)*8 = 8（1ページ目の一番最後のLvの値は8）
 Lv.<%= @base_level + i %>とすることで（I=1,2…と順番に入るため）2ページ目は
Lv.9,10…と表示できる、ということです。 

このような解釈でコードを入れました。
ご質問の意図とずれていたら申し訳ありません。

2021-06-06 07:12 UTC, mihomatsui commented on app/controllers/movies_controller.rb
> +    @movies = Movie.where(genre: ["basic", "git", "ruby", "rails"]).order(id: :asc).page(params[:page]).per(PER)
scopeを使った書き方に修正いたしました。

2021-06-08 06:19 UTC, ajk0421 approved these changes
OKです！

https://github.com/yanbaru-expert/team_project_48/pull/47/files#r645997767

こちらですが、今回はこのままでOKですが、本来であればこういったロジックは `decorater` というのを使用します！

もし時間があれば調べてみてください！

2021-06-08 13:44 UTC, mihomatsui commented
ありがとうございます！
 decorater について調べておきます。

2021-06-08 13:44 UTC, merged