テキスト教材の読破済みボタンを実装
yanbaru-expert/team_project_48 pull request #50
Opened 2021-06-22 11:53 UTC by takayanagi-takesi

## issue 番号

（例）
close #39

## 実装内容
・読破済み/読破済みを解除ボタンを実装

## 参考資料（必要があれば）
動画教材の視聴済みボタンを実装 #45

- [やんばるエキスパート教材 モデルの関連付け その2(多対多)](https://www.yanbaru-code.com/texts/297)
- [多対多のモデルの実装、コントローラー、ビューの書き方](https://qiita.com/tanutanu/items/1607627d475072701247)

## チェックリスト

【補足】プルリクを出した後，クリックしてチェックを入れて下さい

- [ ] GitHub で Files changed を確認
- [ ] 影響し得る範囲のローカル環境での動作確認

## スクリーンショット（必要があれば）
![スクリーンショット 2021-06-22 20 49 57](https://user-images.githubusercontent.com/75218115/122919922-c39a6800-d39b-11eb-9b02-e0c357afc9cd.png)
![スクリーンショット 2021-06-22 20 49 33](https://user-images.githubusercontent.com/75218115/122919989-d57c0b00-d39b-11eb-8f7a-f45d0751701f.png)

## 備考（必要があれば）

2021-06-23 14:19 UTC, naotsugukaneko commented on app/views/texts/_text.html.erb
> +            <%= render "read", text: text.id %>
インデントずれてないでしょうか？

2021-06-23 14:19 UTC, naotsugukaneko commented on app/controllers/reads_controller.rb
> +    @text = Text.find(params[:text_id])
一覧ページを表示した際にN+1問題が発生してしまっています！

2021-06-24 00:50 UTC, takayanagi-takesi commented on app/controllers/reads_controller.rb
> +    @text = Text.find(params[:text_id])
なるほど！！この前言ってくれてたやつですね！！
ありがとうございます！！

2021-06-24 00:51 UTC, takayanagi-takesi commented on app/views/texts/_text.html.erb
> +            <%= render "read", text: text.id %>
すみません。

2021-06-25 04:18 UTC, mihomatsui commented on app/controllers/reads_controller.rb
> +    @text = Text.find(params[:text_id])
createアクションにも同じコードがあるので、以前の[動画教材の視聴済みボタンを実装 #45](https://github.com/yanbaru-expert/team_project_48/pull/45/files)の
`watches_controller.rb`のようにbefore_actionでまとめた方が良いのではないか？と思いました。

2021-07-04 04:18 UTC, mihomatsui commented on config/routes.rb
>    resources :texts
ここのコードは不要だと思います。
参考：[モデルの関連付けその2:多対多](https://www.yanbaru-code.com/texts/297)

2021-07-04 05:28 UTC, takayanagi-takesi commented on config/routes.rb
>    resources :texts
ありがとうございます！！

2021-07-05 06:09 UTC, ajk0421 requested changes

2021-07-05 06:09 UTC, ajk0421 commented on app/controllers/reads_controller.rb
> +    current_user.reads.find_by(text_id: @text.id).destroy!
```
current_user.reads.find_by(text_id: @text.id).destroy!
```
- レコード取得
- レコード削除

はワンライナーで書かない方がいいです！

2021-07-05 06:09 UTC, ajk0421 commented on app/controllers/texts_controller.rb
> +    @texts = Text.where(genre: ["basic", "git", "ruby", "rails"]).includes(:reads)
```
.where(genre: ["basic", "git", "ruby", "rails"])
```
このクエリは `scope` にしちゃいましょう！

2021-07-06 04:13 UTC, takayanagi-takesi commented on app/controllers/texts_controller.rb
> +    @texts = Text.where(genre: ["basic", "git", "ruby", "rails"]).includes(:reads)
確認ありがとうございます。
1点質問お願いいたします。
この`scope`は長くなりそうならmodelにも書こう！！という判断基準で書くといいのでしょうか？

2021-07-06 04:13 UTC, takayanagi-takesi commented on app/controllers/reads_controller.rb
> +    current_user.reads.find_by(text_id: @text.id).destroy!
確認ありがとうございます。承知いたしました。

2021-07-06 04:44 UTC, ajk0421 requested changes

2021-07-06 04:44 UTC, ajk0421 commented on app/models/text.rb
> +  scope :text_include, -> { includes(:reads)}
https://github.com/yanbaru-expert/team_project_48/pull/52#discussion_r664230521

こちら参考にしてくだい！

2021-07-06 04:58 UTC, takayanagi-takesi commented on app/models/text.rb
> +  scope :text_include, -> { includes(:reads)}
汎用性の高いものだけ`scope`にするということですよね。
ありがとうございます！！

2021-07-06 07:20 UTC, ajk0421 requested changes

2021-07-06 07:20 UTC, ajk0421 commented on app/models/text.rb
> +  scope :text_show, -> { where(genre: ["basic", "git", "ruby", "rails"]) }
下記の実装を参考にしてください！
https://github.com/yanbaru-expert/team_project_48/blob/develop/app/controllers/movies_controller.rb#L4

2021-07-06 07:20 UTC, ajk0421 commented on app/controllers/texts_controller.rb
> +    @texts = Text.active.includes(:reads)
動作確認しましたか？

2021-07-06 07:30 UTC, takayanagi-takesi commented on app/controllers/texts_controller.rb
> +    @texts = Text.active.includes(:reads)
申し訳ありません。
焦ってしたつもりでいてました。

2021-07-09 09:39 UTC, ajk0421 approved these changes

2021-07-09 13:07 UTC, merged