ransackを用いて動画教材の検索機能を実装
yanbaru-expert/team_project_48 pull request #52
Opened 2021-06-23 08:59 UTC by naotsugukaneko

## issue 番号
close #49 

## 実装内容
- 動画教材の検索機能
  - gem 'ransack'を導入
  - タイトル名の部分検索可能

## 参考資料
- 検索機能
  - [やんばるエキスパート](https://www.yanbaru-code.com/texts/221)

## チェックリスト
- [ ] GitHub で Files changed を確認
- [ ] 影響し得る範囲のローカル環境での動作確認

## スクリーンショット（必要があれば）
- タイトル下に検索バー追加(動画教材の一覧ページ)
<img width="1477" alt="スクリーンショット 2021-06-23 17 36 12" src="https://user-images.githubusercontent.com/77927517/123067816-4844bf00-d44c-11eb-92d6-b83d1f6929d4.png">
- 検索後
<img width="1491" alt="スクリーンショット 2021-06-23 17 36 34" src="https://user-images.githubusercontent.com/77927517/123067855-5266bd80-d44c-11eb-849c-e667322f3ac6.png">

## 備考
- オリジナルアプリの教材検索には劣る形での実装となりました
   - 自動検索しない
   - 非同期処理が未実装(空で検索して元の一覧ページに戻る)

2021-06-25 07:05 UTC, mihomatsui commented on app/controllers/movies_controller.rb
> +    @movies = @q.result.where(genre: ["basic", "git", "ruby", "rails"]).includes(:watches).order(id: :asc).recent.page(params[:page]).per(PER)
以前[Rails動画教材ページのページネーションの実装 #47](https://github.com/yanbaru-expert/team_project_48/pull/47)で`app/models/movie.rb`にscope(=recent)を設定していて、
内容が重複しているので変更をお願いします。

2021-06-26 15:19 UTC, naotsugukaneko commented on app/controllers/movies_controller.rb
> +    @movies = @q.result.where(genre: ["basic", "git", "ruby", "rails"]).includes(:watches).order(id: :asc).recent.page(params[:page]).per(PER)
重複してる部分の変更を実施しました！
モデル内のscopeに`includes(:watches)`を追記しました。

2021-06-26 15:19 UTC, naotsugukaneko commented on app/views/movies/index.html.erb
> +  <% end %>
案を出して頂きありがとうございます！
そのまま頂き変更しました🙇‍♂️

2021-06-26 16:13 UTC, naotsugukaneko commented on app/views/movies/index.html.erb
> +  <% end %>
[<rails>戻るボタンの実装](https://tomo-bb-aki0117115.hatenablog.com/entry/2020/11/22/224927)
こちらのサイトを参考に戻るボタンも実装してみました！
<img width="1424" alt="スクリーンショット 2021-06-27 1 07 40" src="https://user-images.githubusercontent.com/77927517/123519224-ec489780-d6e4-11eb-9e5a-db9388d4c0bf.png">

2021-06-29 00:59 UTC, mihomatsui commented on app/views/movies/index.html.erb
> +  <% end %>
提案した戻るボタンの実装、追加して頂きありがとうございます！
`教材を探す`とあるととてもわかりやすいですね。

提案と質問が計2点あります。

- 押し間違いを防ぐため、ボタン同士の間隔を空けることはできますか？
- `教材を探す`ですが、naotsuguさんのコードを見ると虫眼鏡（🔍）がついていますが、スクリーンショットには
なさそうですがこれで良かったですか？？（naotsuguさんは虫眼鏡付けたかったのかなと思いまして...）

2021-06-29 05:15 UTC, naotsugukaneko commented on app/views/movies/index.html.erb
> +  <% end %>
[この記事](https://ymgsapo.com/2018/11/19/place-regular-interval/)を参考にボタンの間隔をあけました！

2021-06-29 10:17 UTC, mihomatsui commented on app/views/movies/index.html.erb
> +  <% end %>
スクリーンショット、貼り直して頂いたのですね。ありがとうございます！
あと間隔も良いと思います。参考のサイトのリンクもありがとうございます。

2021-07-01 05:43 UTC, ajk0421 requested changes

2021-07-01 05:43 UTC, ajk0421 commented on app/models/movie.rb
> +  scope :recent, -> { where(genre: ["basic", "git", "ruby", "rails"]).includes(:watches).order(id: :asc) }
```
.includes(:watches)
```

`scope :recent` を使用する場合、必要な場合もあれば、不必要なことも想定されるので、ここは分けて書きましょう！

2021-07-01 05:43 UTC, ajk0421 commented on app/controllers/movies_controller.rb
>    PER = 8
```
PER = 8
```
すみません。定数はコントローラーに書くべくではないので、モデル移動お願いしても良いでしょうか？

2021-07-01 15:04 UTC, naotsugukaneko commented on app/models/movie.rb
> +  scope :recent, -> { where(genre: ["basic", "git", "ruby", "rails"]).includes(:watches).order(id: :asc) }
`.includes(:watches)` は別でscopeを定義しました！

2021-07-01 15:05 UTC, naotsugukaneko commented on app/controllers/movies_controller.rb
>    PER = 8
そうなんですね💦
勉強になりました！
モデルに修正しております。

2021-07-04 02:10 UTC, ajk0421 requested changes

2021-07-04 02:10 UTC, ajk0421 commented on app/models/movie.rb
> +  PER = 8
定数はお作法として、クラス定義直下に書きましょう！

2021-07-04 02:10 UTC, ajk0421 commented on app/models/movie.rb
> +  # 1ページに表示される動画教材を定義
```
scope :include, -> { includes(:watches) }
scope :recent, -> { active.include }
```

ここですが、まず、 `scope` とは何か？というところからになるのですが、 `scope` っていうのは簡単にいうと、

```
where(genre: ["basic", "git", "ruby", "rails"]).order(id: :asc)
```
こういったクエリを複数回書く可能性がある場合、一回一回書くのは面倒なので、

```
scope :active, -> { where(genre: ["basic", "git", "ruby", "rails"]).order(id: :asc) }
```

こんな感じでまとめて書いておきましょう！

というものです。

それを踏まえてなんですが、今回は、movieのindex画面で呼び出すとき、 `includes(:watches)` が必要になりますが、

ある画面では、 `active.includes(:watches, :hoge)` が必要。
また、ある画面では、 `active.includes(:hoge, :fuga)`が必要。
また、ある画面では、 `active.includes(:watches,, :hoge, :fuga)` が必要。

となった場合、どのように記述すれば良いでしょうか？

ちょっと考えてみて下さい！

2021-07-04 02:10 UTC, ajk0421 commented on app/controllers/movies_controller.rb
> +    @base_level = (page_num - 1) * Movie::PER
```
Movie::PER
```
ここって
```
PER
```
だと呼び出せないですかね？？(確認でした！)

2021-07-04 05:13 UTC, naotsugukaneko commented on app/models/movie.rb
> +  PER = 8
ありがとうございます！
`class Movie < ApplicationRecord
  # 1ページに表示される動画教材を定義
  PER = 8
  has_many :watches, dependent: :destroy
  has_many :watched_users, through: :watches, source: :user
  `
クラス直下に修正しました！

2021-07-04 05:15 UTC, naotsugukaneko commented on app/controllers/movies_controller.rb
> +    @base_level = (page_num - 1) * Movie::PER
> ここって
> `PER`
> だと呼び出せないですかね？？(確認でした！)
エラーとなり`Movie::PER`なら動作しました💦
下記エラーです。
<img width="1046" alt="スクリーンショット 2021-07-04 13 12 39" src="https://user-images.githubusercontent.com/77927517/124373985-4d1e3400-dcd2-11eb-8ce5-ce562cd1759b.png">

2021-07-06 04:41 UTC, ajk0421 requested changes

2021-07-06 04:41 UTC, ajk0421 commented on app/controllers/movies_controller.rb
> +    @base_level = (page_num - 1) * Movie::PER
👍

2021-07-06 04:41 UTC, ajk0421 commented on app/models/movie.rb
> +  # 1ページに表示される動画教材を定義
ここ、少し答えに近い感じで言うと、ここで、 scope にした方がいいのは
```
scope :active, -> { where(genre: ["basic", "git", "ruby", "rails"]).order(id: :asc) }
```
この部分だけです！

何故かというと

```
scope :include, -> { includes(:watches) }
```

このように定義した場合

>ある画面では、 active.includes(:watches, :hoge) が必要。
>また、ある画面では、 active.includes(:hoge, :fuga)が必要。
>また、ある画面では、 active.includes(:watches,, :hoge, :fuga) が必要。

この度にscopeを定義しなければなく、そうなると、そもそものscopeの旨味が無いので、ここは素直に

```
active.includes(:watches, :hoge) 
active.includes(:hoge, :fuga)
active.includes(:watches,, :hoge, :fuga)
```
こういう風に個々で呼び出すのがベターです！

2021-07-06 05:24 UTC, naotsugukaneko commented
よく理解できました🙇‍♂️
おっしゃって頂いている通りわざわざscopeで定義する意味がないですね💦

教えて頂きありがとうございます！！

2021-07-06 05:27 UTC, ajk0421 requested changes

2021-07-06 05:27 UTC, ajk0421 commented on app/models/movie.rb
> +  #movieをuserが視聴済みにしている時はtrue,していcdない時はfalse
👀

2021-07-06 05:31 UTC, naotsugukaneko commented on app/models/movie.rb
> +  #movieをuserが視聴済みにしている時はtrue,していcdない時はfalse
つめが甘く申し訳ありません💦
修正しました🙇‍♂️

2021-07-06 05:33 UTC, ajk0421 approved these changes

2021-07-06 05:35 UTC, merged