トップページの実装
yanbaru-expert/team_project_48 pull request #63
Opened 2021-07-17 07:57 UTC by itstoasted-0

## issue 番号

close #62 

## 実装内容

- トップページの実装（フロント）
  - チーム紹介トップページ
  - ヘッダーデザイン変更（ヘッダーアイコン、文字色、フォント等）
  - ゲストログインボタン設置
  - ソースコードのリンク設置
  - メディアクエリを使ったレスポンシブ対応

## 参考資料（必要があれば）

- トップページ
  - [メディアクエリ基礎](https://qiita.com/okazania/items/248506542fa12c8edc20)
  - [メディアクエリ変数](https://www.tam-tam.co.jp/tipsnote/html_css/post10708.html)
  - [css 円形切り抜き](https://blog.ver001.com/css-image-border-radius-object-fit/)
  - [css 読み込み順序](https://qiita.com/k152744/items/2f414b79eaf6b8a730c3)
  - [カラー参考（デザイン）](https://color.adobe.com/ja/explore)
  - [html構成、クラス名など参考（楽天公式サイト）](https://corp.rakuten.co.jp/careers/interview/)

## チェックリスト

- [ ] GitHub で Files changed を確認
- [ ] 影響し得る範囲のローカル環境での動作確認

## スクリーンショット
![スクリーンショット 2021-07-17 16 40 17](https://user-images.githubusercontent.com/75562508/126030338-93a5d1c9-523b-4f99-807c-5bd58088bdce.png)
![スクリーンショット 2021-07-17 16 44 53](https://user-images.githubusercontent.com/75562508/126030339-f34f3589-5afb-4c55-9b85-9c922e77d8ac.png)

## 備考

2021-07-18 13:56 UTC, takayanagi-takesi commented
ローカルで表示しようとしたら下記のエラーがでてしまいます。
application.cssのコンパイルをしてくださいということでしょうか？

`  
ActionView::Template::Error (application.css):
     5:     <meta name="viewport" content="width=device-width,initial-scale=1">
     6:     <%= csrf_meta_tags %>
     7:     <%= csp_meta_tag %>
     8:     <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
     9:     <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    10:     <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.9.0/css/all.css">
    11:     <%= favicon_link_tag('favicon.ico') %>`


![スクリーンショット 2021-07-18 22 51 45](https://user-images.githubusercontent.com/75218115/126069933-3dc8c913-4751-4802-9238-d7475031f8e9.png)

2021-07-27 05:50 UTC, ajk0421 requested changes

2021-07-27 05:50 UTC, ajk0421 commented on app/views/layouts/application.html.erb
> +    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.9.0/css/all.css">
fontawesomeの導入はjsのライブラリかgemで導入しましょう！

2021-07-28 11:01 UTC, itstoasted-0 commented on app/views/layouts/application.html.erb
> +    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.9.0/css/all.css">
@ajk0421 yarnを使ってfontawesomeを導入致しました。

2021-08-04 05:38 UTC, ajk0421 approved these changes

2021-08-04 10:10 UTC, merged