ページの最上部に戻るボタンを設定（途中）
yanbaru-expert/team_project_48 pull request #64
Opened 2021-07-22 11:18 UTC by mihomatsui

## issue 番号

close #59

## 実装内容

- ページの最上部に戻るボタンを設定
  - fontawesomeの導入
  - yarnでjQueryを導入
  - environment.jsの編集
  - application.jsの編集
  - custom.jsの作成と読み込みの記述を追記
  -  ボタンを設置
  - 非推奨のclick、scrollイベントを修正

## 参考資料
- ページの最上部に戻るボタンを設定
  - [jQueryの導入・挙動確認](https://www.yanbaru-code.com/texts/219)
  - [[jQuery] トップへ戻るボタンの実装サンプル(コードの書き方を参考)](https://agohack.com/page-top-button-css-jquery/)

## チェックリスト
- [ ] GitHub で Files changed を確認
- [ ] 影響し得る範囲のローカル環境での動作確認

## スクリーンショット
<img width="500" alt="最上部に戻るボタン" src="https://user-images.githubusercontent.com/70443334/126630444-a5d06518-aad6-4ab4-8591-53323380f2c5.png">

## 備考
今詰まっていること→jQueryが初回以外動作しない？
rails sでサーバーを起動して、最初の`texts#index`のページ上ではスクロールしたらボタンが現れて、ボタンを
押すと最上部に戻りボタンが消える。しかし、別のページに移動するとボタンは最初から表示されている。
そして、再度`texts#index`を読み込むと、先ほどは非表示状態だったボタンが最初から表示されてしまう。

2021-07-24 05:03 UTC, itstoasted-0 reviewed
Turbolinksを消さないやり方をコメントしました。

2021-07-24 05:03 UTC, itstoasted-0 commented on app/javascript/custom.js
> +$(function () {
$(function(){
  // 処理内容 
});

↓　以下のように編集

$(document).on('turbolinks:load', function() {
  // 処理内容
});

2021-07-24 14:36 UTC, mihomatsui commented on app/javascript/custom.js
> +$(function () {
ありがとうございます！
コードを修正しました。

2021-07-25 14:52 UTC, itstoasted-0 commented on app/views/layouts/application.html.erb
> +      <div id="page_top"><a href="#"></a></div>
`<div id="page_top class="mb-5"><a href="#"></a></div>`

簡易的にbootstrapのcssでmarginを入れるとどうでしょうか？

2021-07-26 03:09 UTC, mihomatsui commented on app/views/layouts/application.html.erb
> +      <div id="page_top"><a href="#"></a></div>
うっきさん
コメントありがとうございます！試したところ、最後までスクロールしてもボタンが消えなくなりました。
![cssyohakuari](https://user-images.githubusercontent.com/70443334/126927476-e83f3d1d-194e-4489-ade6-c16df92fe398.gif)

> （不確定ですが自分が現在プルリク中のデザインでは、ヘッダーの背景色を消しているので被らないかも？しれません）
確かにそうですね。うっきさんのプルリク分をマージしてから検討しても良いのかも？と思いました。

2021-08-09 03:39 UTC, ajk0421 requested changes

2021-08-09 03:39 UTC, ajk0421 commented on app/assets/stylesheets/application.scss
> +  margin: auto;
せっかく `scss` なんで、以下の用に書いても良いと思います！

```
#page_top {
  width: 50px;
  height: 50px;
  position: fixed;
  right: 20px;
  bottom: 30px;
  background: #f2ac57;
  opacity: 0.6;
  border-radius: 50%;
  a {
    position: relative;
    display: block;
    width: 50px;
    height: 50px;
    text-decoration: none;
    text-align: center;
    &::before {
      font-family: "Font Awesome 5 Free";
      content: "\f106";
      font-weight: 900;
      font-size: 25px;
      color: #fff;
      position: absolute;
      width: 25px;
      height: 25px;
      top: 10px;
      bottom: 25px;
      right: 0;
      left: 0;
      margin: auto;
    }
  }
}
```

2021-08-09 03:39 UTC, ajk0421 commented on app/javascript/custom.js
> +});
こちらですが、今後、この「TOPへ戻る」以外の実装は追加されませんか？
もしされないのであれば、ファイル名変えた方がいいですし、されるのであれば、処理をfunctionでまとめた方が良いですね！

2021-08-10 11:05 UTC, mihomatsui commented on app/assets/stylesheets/application.scss
> +  margin: auto;
詳しく教えて頂き、ありがとうございます。
修正しました！

2021-08-10 11:07 UTC, mihomatsui commented on app/javascript/custom.js
> +});
> こちらですが、今後、この「TOPへ戻る」以外の実装は追加されませんか？

追加の実装の予定がないので`pagetop_button.js`に名前を変更しました。

2021-08-11 06:00 UTC, ajk0421 approved these changes

2021-08-11 06:36 UTC, merged