ページ全体の設定を追加
yanbaru-expert/team_project_48 pull request #8
Opened 2021-04-12 06:17 UTC by naotsugukaneko

## issue 番号
close #4 

## 実装内容
- ページ全体の設定を追加
  - 幅の設定
  - フォントサイズの設定

## チェックリスト
- [ ] GitHub で Files changed を確認
- [ ] 影響し得る範囲のローカル環境での動作確認

2021-04-12 06:29 UTC, ajk0421 requested changes

2021-04-12 06:29 UTC, ajk0421 commented on .gitignore
> +/vendor/bundle
```
/vendor/bundle
```
同じ記述がありませんか？

2021-04-12 06:29 UTC, ajk0421 commented on app/helpers/application_helper.rb
> +end
インデント、ズレていませんか？

2021-04-12 06:29 UTC, ajk0421 commented on config/environments/development.rb
> +  config.hosts << ".amazonaws.com"
これはどういった理由で追加されましたか？？

2021-04-12 23:42 UTC, naotsugukaneko commented on .gitignore
> +/vendor/bundle
確認不足で削除しました。

2021-04-12 23:43 UTC, naotsugukaneko commented on app/helpers/application_helper.rb
> +end
半角2スペースに変更しました。以後半角2スペース徹底します！

2021-04-12 23:43 UTC, naotsugukaneko commented on config/environments/development.rb
> +  config.hosts << ".amazonaws.com"
slackで頂いたご回答、理解しました。
一旦削除しましたのでまた今後の動作確認の際に追加します。

2021-04-13 02:22 UTC, ajk0421 approved these changes
OKですが、 `.gitignoer` の修正だされていませんでした？

2021-04-13 02:31 UTC, naotsugukaneko commented
> OKですが、 `.gitignoer` の修正だされていませんでした？
出してました。
コミットメーセージが足りないということでしょうか？
申し訳ありません。。以後気を付けます。

2021-04-13 02:37 UTC, ajk0421 commented
> > OKですが、 `.gitignoer` の修正だされていませんでした？
> 
> 出してました。
> コミットメーセージが足りないということでしょうか？
> 申し訳ありません。。以後気を付けます。

あ、いえ、僕が気になったのは

```
/vendor/bundle
```

この記述は既にあったので、必要無いのでは？
というものでした！

他の箇所に関しては

2021-04-13 02:40 UTC, merged